[project]
name = "tykitools"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "click>=8.1.8",
    "requests>=2.32.3",
    "ruff>=0.9.7",
    "setuptools>=75.8.1",
    "twine>=6.1.0",
    "wheel>=0.45.1",
]
